"""added a token table which is linked to the user

Revision ID: 0292301f9d7f
Revises: 99d7ff4e5c01
Create Date: 2026-03-04 07:31:25.852482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0292301f9d7f'
down_revision: Union[str, Sequence[str], None] = '99d7ff4e5c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
