"""teicked thr trade table by creating a relation between trade and strategy table

Revision ID: 07d90ffb27dc
Revises: 0f9e3009e8e0
Create Date: 2026-03-07 05:42:07.876132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07d90ffb27dc'
down_revision: Union[str, Sequence[str], None] = '0f9e3009e8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('strategy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trades', 'strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    op.drop_column('trades', 'strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('strategy', postgresql.ENUM('scalping', 'day_trading', 'swing_trading', 'position_trading', name='strategyenum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('trades', 'strategy_id')
    # ### end Alembic commands ###
