"""just made the strategies table 

Revision ID: 66f7f3d19c7f
Revises: 616d181ccc4e
Create Date: 2026-03-05 12:45:50.951506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f7f3d19c7f'
down_revision: Union[str, Sequence[str], None] = '616d181ccc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'strategies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'user_id')
    # ### end Alembic commands ###
