"""made the account tabele and made some changes in the trade relationships

Revision ID: 880bc3acdc19
Revises: fdce92cb8b29
Create Date: 2026-03-04 22:32:49.862049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880bc3acdc19'
down_revision: Union[str, Sequence[str], None] = 'fdce92cb8b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('trades_user_id_fkey'), 'trades', type_='foreignkey')
    op.drop_column('trades', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('trades_user_id_fkey'), 'trades', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
