"""added a token table which is linked to the user

Revision ID: 99d7ff4e5c01
Revises: ac8d033ddee7
Create Date: 2026-03-04 07:27:42.797326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99d7ff4e5c01'
down_revision: Union[str, Sequence[str], None] = 'ac8d033ddee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'entry',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trades', 'exit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trades', 'stop_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trades', 'take_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trades', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('trades', 'time_frame',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('trades', 'session',
               existing_type=postgresql.ENUM('London', 'New_York', 'Asia', name='sessionenum'),
               nullable=True)
    op.alter_column('trades', 'strategy',
               existing_type=postgresql.ENUM('scalping', 'day_trading', 'swing_trading', 'position_trading', name='strategyenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'strategy',
               existing_type=postgresql.ENUM('scalping', 'day_trading', 'swing_trading', 'position_trading', name='strategyenum'),
               nullable=False)
    op.alter_column('trades', 'session',
               existing_type=postgresql.ENUM('London', 'New_York', 'Asia', name='sessionenum'),
               nullable=False)
    op.alter_column('trades', 'time_frame',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('trades', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trades', 'take_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trades', 'stop_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trades', 'exit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trades', 'entry',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
