"""realized my account dont have a name which is essencial so change stuff to fit

Revision ID: a85c39d7a548
Revises: 96f628c1ec96
Create Date: 2026-03-05 00:20:32.722321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85c39d7a548'
down_revision: Union[str, Sequence[str], None] = '96f628c1ec96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'name')
    # ### end Alembic commands ###
